apiVersion: v1
kind: Service
metadata:
  name: object-storage--storage-service
  namespace: test
  labels:
    app: object-storage
spec:
  ports:
    - port: 8888
      name: grpc
      targetPort: 8888
  # clusterIP: None
  type: ClusterIP
  selector:
    name: object-storage--storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-storage--storage
  namespace: test
  labels:
    app: object-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      name: object-storage--storage
  template:
    metadata:
      labels:
        name: object-storage--storage
        app: docker-registry
    spec:
      containers:
        - name: storage
          image: docker.liukexin.com/artificial/object_storage.storage.storage@sha256:e29d43bb10a786448ee2a479871a73c2b5dfb499704f49819eb01239a8cc0569
          ports:
            - containerPort: 8888
              name: grpc
          env:
            - name: UPTRACE_DSN 
              value: http://test_secret_token@uptrace-service.default:4318?grpc=4317
            - name: UPTRACE_ENDPOINT
              value: uptrace-service.default:4317


---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: object-storage-route
  namespace: test
spec:
  parentRefs:
    - name: http-gateway
      namespace: test
  hostnames: ["object-test.liukexin.com"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: object-storage--gateway-service
          port: 443

---

apiVersion: v1
kind: Service
metadata:
  name: object-storage--gateway-service
  namespace: test
  labels:
    app: object-storage
spec:
  ports:
    - port: 443
      name: https
      targetPort: 443
  # clusterIP: None
  type: ClusterIP
  selector:
    name: object-storage--gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-storage--gateway
  namespace: test
  labels:
    app: object-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      name: object-storage--gateway
  template:
    metadata:
      labels:
        name: object-storage--gateway
        app: docker-registry
    spec:
      containers:
        - name: storage
          image: docker.liukexin.com/artificial/object_storage.gateway.gateway@sha256:dbc4962a1bd95f2e698024bd23147bdea957904d64465bbad010c32294e2f615
          ports:
            - containerPort: 443
              name: https
          env:
            - name: UPTRACE_DSN 
              value: http://test_secret_token@uptrace-service.default:4318?grpc=4317
            - name: UPTRACE_ENDPOINT
              value: uptrace-service.default:4317
