apiVersion: v1
kind: Service
metadata:
  name: object-storage--storage-service
  namespace: test
  labels:
    app: object-storage
spec:
  ports:
    - port: 8888
      name: grpc
      targetPort: 8888
  # clusterIP: None
  type: ClusterIP
  selector:
    name: object-storage--storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-storage--storage
  namespace: test
  labels:
    app: object-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      name: object-storage--storage
  template:
    metadata:
      labels:
        name: object-storage--storage
        app: docker-registry
    spec:
      containers:
        - name: storage
          image: docker.liukexin.com/artificial/object_storage.storage.storage@sha256:29356d06c771211fea3d2b8a47bc74160995b8c06114ae6b273bc0546c1690b4
          ports:
            - containerPort: 8888
              name: grpc


---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: object-storage-route
  namespace: test
spec:
  parentRefs:
    - name: http-gateway
      namespace: test
  hostnames: ["object-test.liukexin.com"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: object-storage--gateway-service
          port: 443

---

apiVersion: v1
kind: Service
metadata:
  name: object-storage--gateway-service
  namespace: test
  labels:
    app: object-storage
spec:
  ports:
    - port: 443
      name: https
      targetPort: 443
  # clusterIP: None
  type: ClusterIP
  selector:
    name: object-storage--gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-storage--gateway
  namespace: test
  labels:
    app: object-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      name: object-storage--gateway
  template:
    metadata:
      labels:
        name: object-storage--gateway
        app: docker-registry
    spec:
      containers:
        - name: storage
          image: docker.liukexin.com/artificial/object_storage.gateway.gateway@sha256:ef4502f35b0b44038f1a323431a60e08be3f2c0dd2bd3c6c92443a17934f8589
          ports:
            - containerPort: 443
              name: https
